name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/home/mkoutny/containers/opensuse_containers_tumbleweed_containers/rapido-ci:latest
      env:
        KERNEL_RELEASE: 6.16.7-1-default
        KERNEL_INSTALL_MOD_PATH: /usr/
      options:  -w /test
      volumes:
        - ${{ github.workspace }}:/test

    steps:
      - uses: actions/checkout@v4

      - name: Run selftest
        run: |
          /test/selftest/selftest.sh

